/*
 * Copyright 2019 The Glow Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.projectglow.pipelines.dnaseq.alignment

import org.broadinstitute.hellbender.utils.bwa.BwaMemIndex

/**
 * CLI to generate BWA-MEM JNI index image file from existing index files.
 *
 * The index file required by the JNI library is a single "image" file that contains the same
 * information as the set of index files generated by "bwa index".
 */
object GenerateBwaIndexImage {
  def main(args: Array[String]): Unit = {
    if (args.length != 2) {
      sys.error("First argument is path to fasta file with indices; second arg is output file")
    }
    val indexPrefix = args(0)
    val outputPath = args(1)
    BwaMemIndex.createIndexImageFromIndexFiles(indexPrefix, outputPath)
  }
}
